### ISSUE TITLE
"map it" to new tab? best flow?

### ISSUE THREAD

**Issue by tbehrenbeck** [adnanyousef/Where2#45]

**Comment by adnanyousef** [comment]
@tbehrenbeck I think we should open the link in a new tab for now. I can look into updating the current map but not sure if I can get it done by wednesday.

**Comment by llamalord22** [comment]
I'd say the best argument for having it open in a new tab is mostly that this is app would most likely be used on your phone frequently, where having it pull up in google maps would be most convenient.
